services:
  postgres:
    image: postgres:16-alpine
    container_name: ecb_postgres
    environment:
      POSTGRES_USER: ecb_user
      POSTGRES_PASSWORD: ecb_password
      POSTGRES_DB: ecb_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecb_user -d ecb_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
